# Generated by Django 5.2.8 on 2025-12-15 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FYPProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_matric_id', models.CharField(blank=True, max_length=50, verbose_name='Student ID')),
                ('title', models.CharField(max_length=255)),
                ('fyp_stage', models.CharField(choices=[('FYP1', 'Final Year Project 1'), ('FYP2', 'Final Year Project 2')], default='FYP1', max_length=10)),
                ('co_supervisor', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cosupervised_projects', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course')),
                ('examiner', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examined_projects', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(limit_choices_to={'profile__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(limit_choices_to={'profile__role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Full Name')),
                ('role', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('coordinator', 'Coordinator')], default='student', max_length=20)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('examiner', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_examiner', to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(limit_choices_to={'profile__role': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fypproject')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('examiners', models.ManyToManyField(limit_choices_to={'profile__role': 'lecturer'}, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fypproject')),
            ],
        ),
    ]
