# Generated by Django 5.2.8 on 2025-11-24 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fypproject',
            name='co_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cosupervised_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fypproject',
            name='examiner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examined_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fypproject',
            name='student_matric_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Student ID'),
        ),
    ]
