# --- File: backend/api/urls.py (FINAL & COMPLETE) ---

from django.urls import path, include
from rest_framework.routers import DefaultRouter

# Import all your views from the 'views.py' file in the same directory
from .views import (
    CourseViewSet,
    UserViewSet,
    FYPProjectViewSet,
    TimetableBookingViewSet,
    TimetableSlotViewSet,
    export_to_google_sheet,
    send_initial_notification
)

# Initialize the router, which automatically generates URLs for ViewSets
router = DefaultRouter()
router.register(r'courses', CourseViewSet)
router.register(r'users', UserViewSet)
router.register(r'projects', FYPProjectViewSet)
router.register(r'bookings', TimetableBookingViewSet, basename='timetablebooking') # Added basename
router.register(r'slots', TimetableSlotViewSet, basename='timetableslot')

# Define all URL patterns for this 'api' app
urlpatterns = [
    # Include all URLs automatically generated by the router.
    # This creates endpoints like '/api/courses/', '/api/users/', etc.
    path('', include(router.urls)),
    
    # Manually add the paths for your custom function-based views.
    # This creates the endpoint: /api/export-to-sheet/
    path('export-to-sheet/', export_to_google_sheet, name='export-to-sheet'),
    
    # This creates the endpoint: /api/send-notification/
    path('send-notification/', send_initial_notification, name='send-notification'),
]