# --- File: backend/api/urls.py (FINAL FIXED VERSION) ---

from django.urls import path, include
from rest_framework.routers import DefaultRouter

# --- 1. Import your custom function-based views ---
from .views import (
    CourseViewSet,
    UserViewSet,
    FYPProjectViewSet,
    TimetableBookingViewSet,
    TimetableSlotViewSet,
    export_to_google_sheet,  # Import the Google Sheet function
    send_initial_notification # Import the email function
)

# The router for ViewSets remains the same
router = DefaultRouter()
router.register(r'courses', CourseViewSet)
router.register(r'users', UserViewSet)
router.register(r'projects', FYPProjectViewSet)
router.register(r'bookings', TimetableBookingViewSet)
router.register(r'slots', TimetableSlotViewSet)

# Define all URL patterns for the 'api' app
urlpatterns = [
    # First, include all the URLs automatically generated by the router
    path('', include(router.urls)),
    
    # --- 2. Manually add the paths for your custom function-based views ---
    # This creates the endpoint: /api/export-to-sheet/
    path('export-to-sheet/', export_to_google_sheet, name='export-to-sheet'),
    
    # This creates the endpoint: /api/send-notification/
    path('send-notification/', send_initial_notification, name='send-notification'),
]