# --- File: backend/api/urls.py (FINAL & COMPLETE) ---

from django.urls import path, include
from rest_framework.routers import DefaultRouter

# Import all ViewSets and custom function-based views
from .views import (
    CourseViewSet,
    UserViewSet,
    FYPProjectViewSet,
    TimetableBookingViewSet,
    TimetableSlotViewSet,
    export_to_google_sheet,
    send_initial_notification
)

# Router for ViewSets
router = DefaultRouter()
router.register(r'courses', CourseViewSet)
router.register(r'users', UserViewSet)
router.register(r'projects', FYPProjectViewSet)
router.register(r'bookings', TimetableBookingViewSet)
router.register(r'slots', TimetableSlotViewSet)

# Define all URL patterns for the 'api' app
urlpatterns = [
    # Include all URLs automatically generated by the router
    path('', include(router.urls)),
    
    # Manually add the paths for your custom function-based views
    path('export-to-sheet/', export_to_google_sheet, name='export-to-sheet'),
    path('send-notification/', send_initial_notification, name='send-notification'),
]